on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: List directory
      run: ls -la /home/runner/work/trash_hunt
    - name: Build Docker Images
      run: cat Makefile && make dev-images
    - name: Build Dev ENV
      run: make dev
    - name: Run Tests
      run: make test
