on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: List directory
      run: ls -la
    - name: Build Docker Images
      run: make dev-images
    - name: Build Dev ENV
      run: make dev
    - name: Run Tests
      run: make test
